### PR TITLE
remove app from xml views

### PR DESCRIPTION
**Pull request by lboehm**

### CODE REVIEW

**Review by nicogeburek — APPROVED** [review]

**Comment by nicogeburek** [comment]
Hi @lboehm,
one of the tests was failing, because we now miss the `id` in the newly generated view. Could you add `id="<%= isSubgeneratorCall ? 'idAppControl' : viewname %>"` in the `<Page />` tag?
It makes sense to keep the `id` for routing purposes, doesn't it?

**Comment by lboehm** [comment]
Hi @nicogeburek.

I think we have two options:

1. The ID isn't necessary for routing, so we can dismiss it.
2. We can keep the ID, because it doesn't hurt either. But currently the ID is set on the `<App>` (see [this link](https://github.com/ui5-community/generator-ui5-project/blob/919c99dbb05794c7d7d1bd96a4701fda98a829ca/generators/newview/templates/webapp/view/%24ViewName.view.%24ViewEnding#L5)), but the `<App>` was deleted (see [this link](https://github.com/lboehm/generator-ui5-project/blob/5279498c78a1747ea2aaf8d572b8be6049ea6a7d/generators/newview/templates/webapp/view/%24ViewName.view.%24ViewEnding#L5), so we would have to add it to the `<Page>` tag. 

Which way do you prefer?

BTW: when running the unit tests locally, it takes ages and sometimes they're running into timeouts. Is this just me?

**Comment by wridgeu** [comment]
Hi @lboehm 👋

> BTW: when running the unit tests locally, it takes ages and sometimes they're running into timeouts. Is this just me?

It's the same for me, just wanted to throw that out there :P

BR :)

**Comment by nicogeburek** [comment]
Hi @lboehm,

I think I prefer option 2.

And yes, the tests take ages for me too...

**Review by nicogeburek — APPROVED** [review]

**Comment by lboehm** [comment]
Hi @nicogeburek 

I've provided a commit that adds the ID again. I'm facing quite some issues running the unit tests locally. So I hope the tests will now pass. In the meantime I will try to figure out how to run the tests successfully.

BR Lukas

**Comment by nicogeburek** [comment]
https://github.com/ui5-community/generator-ui5-project/issues/21

**Pull request merged**
